process_name: hollow_knight.exe
player_info:
  module_base: UnityPlayer.dll
  base_offset: 0x01F28838
  offsets: [0x0, 0x0, 0x10, 0x18, 0x0, 0x60]
  hp_offset: 0x198
  hp_value_type: 当前仅int32，无需调整。
keybinds:
  left: a
  right: d
  up: w
  down: s
  jump: space
  attack: j
  dash: lshift
  heal: l
  skill: k
  esc: esc
menu:
  quit_to_title:
    event:
      - [esc, 0.1]
      - [up, 0.0]
      - [jump, 0.1]
      - [jump, 5.0]
  load_save:
    event:
      - [jump, 0.5]
      - [jump, 5.0]
  godhome_boss_room:
    hornet:
      event:
        - right: [press, 5.0, 0.0]
        - jump: [hold, 5.0, 1.0]
        - right: [release, 0.0, 0.0]

